In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [ ]:
data=pd.read_csv("https://query.data.world/s/zxtxz5ro2skvafkuaycnh74g5ppp2g")
data.head(1)

Username  ...                                           Url
0  freeCodeCamp  ...  https://github.com/freeCodeCamp/freeCodeCamp

[1 rows x 8 columns]

In [ ]:
data.isnull().sum()

Username              0
Repository Name       0
Description           3
Last Update Date      0
Language            103
Number of Stars       0
Tags                491
Url                   0
dtype: int64

In [ ]:
data=data.drop(["Last Update Date","Number of Stars"],axis=1)
data.head()

Username  ...                                                Url
0     freeCodeCamp  ...       https://github.com/freeCodeCamp/freeCodeCamp
1             twbs  ...                  https://github.com/twbs/bootstrap
2  EbookFoundation  ...  https://github.com/EbookFoundation/free-progra...
3         facebook  ...                  https://github.com/facebook/react
4               d3  ...                           https://github.com/d3/d3

[5 rows x 6 columns]

In [ ]:
data["Tags"]=data["Tags"].replace(',', ' ', regex=True)
data["Description"]=data["Description"].replace(',',' ',regex=True)

In [ ]:
data=data.fillna(" ")
data.head()

Username  ...                                                Url
0     freeCodeCamp  ...       https://github.com/freeCodeCamp/freeCodeCamp
1             twbs  ...                  https://github.com/twbs/bootstrap
2  EbookFoundation  ...  https://github.com/EbookFoundation/free-progra...
3         facebook  ...                  https://github.com/facebook/react
4               d3  ...                           https://github.com/d3/d3

[5 rows x 6 columns]

In [ ]:
def combined_features(row):
    return row['Repository Name']+" "+row['Language']+" "+row['Tags']+row['Description']
data["combined_features"] = data.apply(combined_features, axis =1)

In [ ]:
user_text=input(" Enter your interests : ")

 Enter your interests : machine learning


In [ ]:
yes_or_no=input("Do you want a repo in a specific language? Type yes or no: ")
if yes_or_no=="yes":
  user_language_input=input("Enter language/languages: ")
else:
  user_language_input=" "

Do you want a repo in a specific language? Type yes or no: no


In [ ]:
user_text=user_text+ " " + user_language_input

In [ ]:
user_series=pd.Series([user_text])
data_with_User=data["combined_features"].append(user_series,ignore_index=True)
data_with_User


0      freeCodeCamp JavaScript nonprofits certificati...
1      bootstrap JavaScript javascript css html boots...
2      free-programming-books   education list books ...
3      react JavaScript  A declarative  efficient  an...
4      d3 JavaScript visualizationBring data to life ...
                             ...                        
976    http-prompt Python python syntax-highlighting ...
977    masscan C  TCP port scanner  spews SYN packets...
978    mint-ui Vue vue mobile component vue-component...
979    iina Swift macos video mpv swift video-playerT...
980                                   machine learning  
Length: 981, dtype: object

In [ ]:
data.head(50)

Username  ...                                  combined_features
0      freeCodeCamp  ...  freeCodeCamp JavaScript nonprofits certificati...
1              twbs  ...  bootstrap JavaScript javascript css html boots...
2   EbookFoundation  ...  free-programming-books   education list books ...
3          facebook  ...  react JavaScript  A declarative  efficient  an...
4                d3  ...  d3 JavaScript visualizationBring data to life ...
5            getify  ...  You-Dont-Know-JS JavaScript book-series javasc...
6        tensorflow  ...  tensorflow C++ tensorflow python machine-learn...
7      sindresorhus  ...  awesome   lists awesome unicorns resources awe...
8             vuejs  ...  vue JavaScript javascript vue framework fronte...
9           angular  ...  angular.js JavaScript  AngularJS - HTML enhanc...
10     robbyrussell  ...  oh-my-zsh Shell zsh-configuration shell theme ...
11           airbnb  ...  javascript JavaScript arrow-functions javascri...
12           github  ...  gitignore   gitignore gitA collection of usefu...
13      FortAwesome  ...  Font-Awesome HTML  The iconic font and CSS too...
14         facebook  ...  react-native JavaScript  A framework for build...
15         electron  ...  electron C++ html css javascript electron c-pl...
16         torvalds  ...                  linux C  Linux kernel source tree
17           jquery  ...       jquery JavaScript  jQuery JavaScript Library
18          jwasham  ...  coding-interview-university    A complete comp...
19             moby  ...  moby Go docker go containersMoby Project - a c...
20          daneden  ...  animate.css CSS css-animations stylesheets css...
21            apple  ...          swift C++  The Swift Programming Language
22             atom  ...  atom CoffeeScript linux macos atom javascript ...
23           meteor  ...  meteor JavaScript javascript meteor npm mongod...
24             h5bp  ...  html5-boilerplate JavaScript  A professional f...
25           nodejs  ...  node JavaScript javascript nodejs windows maco...
26           nodejs  ...  node-v0.x-archive    Moved to https://github.c...
27            rails  ...  rails Ruby rails ruby html mvc activerecord ac...
28     Semantic-Org  ...  Semantic-UI JavaScript semantic flexbox ui css...
29            vinta  ...  awesome-python Python python awesome collectio...
30          hakimel  ...  reveal.js JavaScript slideshow slides presenta...
31         socketio  ...  socket.io JavaScript  Realtime application fra...
32           mrdoob  ...  three.js JavaScript javascript svg webgl html5...
33          laravel  ...  laravel PHP php laravel frameworkA PHP Framewo...
34        expressjs  ...  express JavaScript javascript nodejs express s...
35          reactjs  ...  redux JavaScript reduxPredictable state contai...
36           moment  ...  moment JavaScript  Parse  validate  manipulate...
37          impress  ...  impress.js JavaScript  It's a presentation fra...
38             nwjs  ...  nw.js C++ intel node-webkit nwjs javascript de...
39            jlevy  ...  the-art-of-command-line    Master the command ...
40          chartjs  ...  Chart.js JavaScript html5-charts chart javascr...
41           google  ...  material-design-icons CSS material sprites ico...
42    jakubroztocil  ...  httpie Python python debugging cli http client...
43       ionic-team  ...  ionic TypeScript ionic javascript angular mobi...
44           jekyll  ...  jekyll Ruby ruby jekyll static-site-generator ...
45        Microsoft  ...  vscode TypeScript electron microsoft editor ty...
46          webpack  ...  webpack JavaScript javascript webpack commonjs...
47           resume  ...  resume.github.com JavaScript  Resumes generate...
48     AFNetworking  ...  AFNetworking Objective-C  A delightful network...
49           golang  ...  go Go go programming-language languageThe Go p...

[50 rows x 7 columns]

In [ ]:
data

Username  ...                                  combined_features
0         freeCodeCamp  ...  freeCodeCamp JavaScript nonprofits certificati...
1                 twbs  ...  bootstrap JavaScript javascript css html boots...
2      EbookFoundation  ...  free-programming-books   education list books ...
3             facebook  ...  react JavaScript  A declarative  efficient  an...
4                   d3  ...  d3 JavaScript visualizationBring data to life ...
..                 ...  ...                                                ...
975          chrisjenx  ...  Calligraphy Java  Custom fonts in Android the ...
976           eliangcs  ...  http-prompt Python python syntax-highlighting ...
977  robertdavidgraham  ...  masscan C  TCP port scanner  spews SYN packets...
978            ElemeFE  ...  mint-ui Vue vue mobile component vue-component...
979           lhc70000  ...  iina Swift macos video mpv swift video-playerT...

[980 rows x 7 columns]

In [ ]:
data.shape

(980, 7)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer()

count_matrix = cv.fit_transform(data_with_User.values.astype('U'))
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
count_matrix.shape

(981, 3551)

In [ ]:
from google.colab import files
#count_matrix=pd.DataFrame(count_matrix)
#count_matrix.to_csv('count_matrix.csv') 
#files.download('count_matrix.csv')

In [ ]:
cosine_sim = cosine_similarity(count_matrix)

In [ ]:
cosine_sim

array([[1.        , 0.03422655, 0.07718294, ..., 0.        , 0.        ,
        0.        ],
       [0.03422655, 1.        , 0.        , ..., 0.028846  , 0.0058431 ,
        0.        ],
       [0.07718294, 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.028846  , 0.        , ..., 1.        , 0.00504901,
        0.        ],
       [0.        , 0.0058431 , 0.        , ..., 0.00504901, 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [ ]:
cosine_sim.shape

(981, 981)

In [ ]:
data["index"]=pd.DataFrame([i for i in range(980)])

In [ ]:
data.head(1)

Username  ... index
0  freeCodeCamp  ...     0

[1 rows x 8 columns]

In [ ]:
user_repo_index=980

In [ ]:
def flatten(t):
    return [item for sublist in t for item in sublist]

In [ ]:
def get_title_from_index(index):
  if len(data[data["index"] == index]["index"])!=0:
    return data[data["index"] == index]["index"].values.tolist()

In [ ]:
def find_similar_repos(user_repo_index):
  similar = list(enumerate(cosine_sim[user_repo_index]))
  sorted_similar= sorted(similar, key=lambda x:x[1], reverse=True)
  print(sorted_similar)
  test_list=[]
  for i in range(len(sorted_similar)):
    test_list.append(get_title_from_index(sorted_similar[i][0]))
  res = []
  for val in test_list:
    if val is not None :
      res.append(val)
  res=flatten(res)
  return res[:15]  



  

In [ ]:
find_similar_repos(user_repo_index)

[(980, 1.0000000000000002), (207, 0.7046696061315245), (79, 0.6738600806539392), (943, 0.6592243585878406), (894, 0.6118662731112386), (6, 0.5170499605150212), (124, 0.5159786873477972), (374, 0.4648899184204822), (170, 0.414885847029979), (629, 0.37238794346137694), (615, 0.3608413389098377), (331, 0.3506023628881475), (382, 0.2608181796698347), (503, 0.23971941437392147), (828, 0.2297089340745087), (474, 0.19424157621466953), (906, 0.17833329754394436), (322, 0.17661391425951842), (135, 0.1763719590392683), (362, 0.17253618190801948), (731, 0.1510462572518834), (918, 0.14976100831405903), (640, 0.13488396582102952), (320, 0.1333823447401299), (794, 0.1332233245619766), (235, 0.13176868651363122), (350, 0.13081573458010734), (775, 0.12420865842850663), (280, 0.10642421291080122), (183, 0.10204687451347924), (279, 0.1017647540196928), (901, 0.10074593967754418), (814, 0.09787864135367835), (118, 0.09341165455654848), (877, 0.08583389282501612), (0, 0.0), (1, 0.0), (2, 0.0), (3, 0.0), (

[207, 79, 943, 894, 6, 124, 374, 170, 629, 615, 331, 382, 503, 828, 474]

In [ ]:
import json

In [ ]:
df=pd.DataFrame(columns=["Username","Repository Name","Description","Language","Tags","Url"])
for i in find_similar_repos(user_repo_index):
  df=pd.DataFrame(df)
  df.loc[len(df.index)] = data.iloc[i,:6]
  

  
  result = df.to_json(orient="records")
  parsed = json.loads(result)
print(json.dumps(parsed, indent=4))

[(980, 1.0000000000000002), (207, 0.7046696061315245), (79, 0.6738600806539392), (943, 0.6592243585878406), (894, 0.6118662731112386), (6, 0.5170499605150212), (124, 0.5159786873477972), (374, 0.4648899184204822), (170, 0.414885847029979), (629, 0.37238794346137694), (615, 0.3608413389098377), (331, 0.3506023628881475), (382, 0.2608181796698347), (503, 0.23971941437392147), (828, 0.2297089340745087), (474, 0.19424157621466953), (906, 0.17833329754394436), (322, 0.17661391425951842), (135, 0.1763719590392683), (362, 0.17253618190801948), (731, 0.1510462572518834), (918, 0.14976100831405903), (640, 0.13488396582102952), (320, 0.1333823447401299), (794, 0.1332233245619766), (235, 0.13176868651363122), (350, 0.13081573458010734), (775, 0.12420865842850663), (280, 0.10642421291080122), (183, 0.10204687451347924), (279, 0.1017647540196928), (901, 0.10074593967754418), (814, 0.09787864135367835), (118, 0.09341165455654848), (877, 0.08583389282501612), (0, 0.0), (1, 0.0), (2, 0.0), (3, 0.0), (

In [ ]:
df

Username  ...                                                Url
0                  ZuzooVn  ...  https://github.com/ZuzooVn/machine-learning-fo...
1             josephmisiti  ...  https://github.com/josephmisiti/awesome-machin...
2                    rasbt  ...  https://github.com/rasbt/python-machine-learni...
3               hangtwenty  ...  https://github.com/hangtwenty/dive-into-machin...
4               tensorflow  ...           https://github.com/tensorflow/tensorflow
5             scikit-learn  ...       https://github.com/scikit-learn/scikit-learn
6                  terryum  ...  https://github.com/terryum/awesome-deep-learni...
7                 fchollet  ...                  https://github.com/fchollet/keras
8   oxford-cs-deepnlp-2017  ...  https://github.com/oxford-cs-deepnlp-2017/lect...
9                 ty4z2008  ...                    https://github.com/ty4z2008/Qix
10           aymericdamien  ...  https://github.com/aymericdamien/TensorFlow-Ex...
11            jmcunningham  ...  https://github.com/jmcunningham/AngularJS-Lear...
12             donnemartin  ...  https://github.com/donnemartin/data-science-ip...
13                   mxgmn  ...      https://github.com/mxgmn/WaveFunctionCollapse
14             Developer-Y  ...    https://github.com/Developer-Y/cs-video-courses

[15 rows x 6 columns]

In [ ]:
import pickle

In [ ]:
with open('model_pkl', 'wb') as files:
    pickle.dump(cv, files)

In [ ]:
with open('model_pkl', 'rb') as f:
    lr=pickle.load(f)